### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by IAHM-COL** [FGMEMBERS/b29#3]
Balance may still be out of touch. All autopilots tested had some trouble making the plane stabilize when vertical control is selected.

**Comment by IAHM-COL** [comment]
Fixed by a previous push by JWocky!
Plane flies much better now in jsbsim.

Thanks Jwocky

**Comment by JWocky** [comment]
How does that work? A useer comments and I get the mail? Kind of an 
automated mailing list thing?

**Comment by IAHM-COL** [comment]
Yes. Overall.
You can "watch " or "unwatch " any repository
That way you will be seeing developments issues with it, or avoid being mail-spammed with aircrafts you do not care at the moment
